apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo-express
  template:
    metadata:
      labels:
        run: mongo-express
    spec:
      containers:
      - name: mongo-express
        imagePullPolicy: IfNotPresent
        image: mongo-express:latest
        ports:
          - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: mongo-express
  name: mongo-express
spec:
  selector:
    run: mongo-express
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32767
